language: nix
nix: 2.2.2
before_script:
  - sudo mkdir /etc/nix && echo 'sandbox = true' | sudo tee /etc/nix/nix.conf
script: nix-build -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/31a6c5a7b507847221598b0d14dd41e935afea4e.tar.gz --expr 'with import <nixpkgs> {}; callPackage ./default.nix { releaseBuild = false; }'